#include "actionbase.h"
#include "breed.h"
#include "dragging.h"
#include "fall.h"
#include "jump.h"
#include "move.h"
#include "look.h"
#include "offset.h"
#include "resist.h"
#include "selector.h"
#include "sequence.h"
#include "simple.h"
#include "transform.h"
#include "stay.h"
#include "scanmove.h"
#include "scanjump.h"
#include "interact.h"
#include "dispose.h"
#include "walkwithie.h"
#include "fallwithie.h"
#include "throwie.h"

// Add new actions here
// for example, #include "example.h"
